name: Test
on:
  push:
  pull_request:
  schedule:
    - cron: '0 7 * * 6'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml'
    - name: Install the dependencies
      run: python3 -m pip install .[dev]
    - name: Build
      run: make test
